print ("Escriu un nombre")
entrada1=input()
numero1=int(entrada1)
print ("Escriu un altre nombre")
entrada2=input()
numero2=int(entrada2)
print ("La suma és:",numero1+numero2)
print ("La resta es :" ,numero1-numero2)
print ("La multiplicación es:" ,numero1*numero2)
print ("La division es:" ,numero1/numero2)
print ("El modul es:" ,numero1%numero2)
