var=input("Escriu un simbol")
if var=="0":print("hola")
if var=="1": print("hola")
if var=="2":print("hola")
if var=="3":print("hola")
if var=="4":print("hola")
if var=="5":print("hola")
if var=="6":print("hola")
if var=="7":print("hola")
if var=="8":print("hola")
if var=="9":print("hola")

